### ISSUE TITLE
include template导致报错

### ISSUE THREAD

**Issue by DeAntiWang** [wechat-miniprogram/skylint#2]
报错信息如下：

```
❌ ENOENT: no such file or directory, open '/Users/xxx/project/projectA/src/components/card/template/normal/normal' Error: ENOENT: no such file or directory, open '/Users/xxx/project/projectA/src/components/card/template/normal/normal'
    at Object.openSync (node:fs:506:3)
    at readFileSync (node:fs:402:35)
    at file:///Users/xxx/.nvm/versions/node/v16.0.0/lib/node_modules/skylint/dist/cli.mjs:1193:18
    at Array.map (<anonymous>)
    at collectTemplate (file:///Users/xxx/.nvm/versions/node/v16.0.0/lib/node_modules/skylint/dist/cli.mjs:1192:20)
    at Object.onVisit (file:///Users/xxx/.nvm/versions/node/v16.0.0/lib/node_modules/skylint/dist/cli.mjs:1166:24)
    at file:///Users/xxx/.nvm/versions/node/v16.0.0/lib/node_modules/skylint/dist/chunks/parser.mjs:213:23
    at Array.forEach (<anonymous>)
    at file:///Users/xxx/.nvm/versions/node/v16.0.0/lib/node_modules/skylint/dist/chunks/parser.mjs:212:13
    at walk$2 (file:///Users/xxx/.nvm/versions/node/v16.0.0/lib/node_modules/skylint/dist/chunks/parser.mjs:133:7)
```

其中路径`projectA/src/components/card/template/normal/normal`为`normal.wxml`文件，提供给`components/card/card.wxml`引用使用，引用方法为`<include src="..."></include>`

**Comment by DongZhouJone** [comment]
希望不检测wxml中引入文件的后缀。wxml消除后缀也是解决包大小问题的一个办法，不太可能不去掉后缀
